import React, { useState, useEffect } from 'react';
import './UploadPage.css';
import { useNavigate, useSearchParams } from 'react-router-dom';

const UploadPage = () => {
  const [image, setImage] = useState(null);
  const [imageFile, setImageFile] = useState(null);
  const [name, setName] = useState('');
  const [category, setCategory] = useState('other');
  const [color, setColor] = useState('');
  const [style, setStyle] = useState('casual');
  const [purchasePrice, setPurchasePrice] = useState('');
  const [purchaseDate, setPurchaseDate] = useState('');
  const [loading, setLoading] = useState(false);
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();

  useEffect(() => {
    const categoryParam = searchParams.get('category');
    if (categoryParam && ['top', 'bottom', 'shoes', 'outerwear', 'accessories', 'other'].includes(categoryParam)) {
      setCategory(categoryParam);
    }
  }, [searchParams]);

  const categories = ['top', 'bottom', 'shoes', 'outerwear', 'accessories', 'other'];
  const styles = ['casual', 'formal', 'sporty', 'elegant', 'bohemian', 'minimalist'];

  const handleImageChange = (e) => {
    const file = e.target.files[0];
    if (file) {
      setImageFile(file);
      setImage(URL.createObjectURL(file));
    }
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    
    if (!imageFile) {
      alert('Please select an image');
      return;
    }

    setLoading(true);

    const formData = new FormData();
    formData.append('image', imageFile);
    formData.append('name', name || 'Untitled Item');
    formData.append('category', category);
    formData.append('color', color || 'unknown');
    formData.append('style', style);
    formData.append('purchase_price', purchasePrice);
    if (purchaseDate) formData.append('purchase_date', purchaseDate);

    try {
      const response = await fetch('http://localhost:5001/api/wardrobe/upload', {
        method: 'POST',
        body: formData
      });

      if (response.ok) {
        const data = await response.json();
        if (data.item) {
          if (data.autoGeneratedCombinations > 0 && data.shouldRedirectToSuggestions) {
            navigate('/suggestions');
          } else {
            navigate('/');
          }
        } else {
          navigate('/');
        }
      } else {
        const errorData = await response.json().catch(() => ({ error: response.statusText }));
        alert('Upload error: ' + (errorData.error || response.statusText));
      }
    } catch (error) {
      console.error('Error uploading:', error);
      alert('An error occurred during upload: ' + error.message);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="upload-page">
      <div className="upload-container">
        <h2>Upload Item</h2>
        <p className="upload-description">Add items to your wardrobe, see outfit suggestions</p>
        
        <form onSubmit={handleSubmit} className="upload-form">
          <div className="form-group">
            <label>Select Image *</label>
            <input 
              type="file" 
              accept="image/*" 
              onChange={handleImageChange}
              required
            />
            {image && (
              <div className="image-preview">
                <img src={image} alt="preview" className="preview" />
              </div>
            )}
          </div>

          <div className="form-group">
            <label>Name (Optional)</label>
            <input 
              type="text" 
              value={name}
              onChange={(e) => setName(e.target.value)}
              placeholder="e.g., White Shirt"
            />
          </div>

          <div className="form-group">
            <label>Category *</label>
            <select 
              value={category}
              onChange={(e) => setCategory(e.target.value)}
              required
            >
              {categories.map(cat => (
                <option key={cat} value={cat}>
                  {cat === 'top' ? 'Top (Shirt, T-shirt, etc.)' :
                   cat === 'bottom' ? 'Bottom (Pants, Skirt, etc.)' :
                   cat === 'shoes' ? 'Shoes' :
                   cat === 'outerwear' ? 'Outerwear (Jacket, Cardigan, etc.)' :
                   cat === 'accessories' ? 'Accessories' : 'Other'}
                </option>
              ))}
            </select>
          </div>

          <div className="form-group">
            <label>Color (Optional)</label>
            <input 
              type="text" 
              value={color}
              onChange={(e) => setColor(e.target.value)}
              placeholder="e.g., White, Black, Blue"
            />
          </div>

          <div className="form-group">
            <label>Style *</label>
            <select 
              value={style}
              onChange={(e) => setStyle(e.target.value)}
              required
            >
              {styles.map(s => (
                <option key={s} value={s}>
                  {s === 'casual' ? 'Casual' :
                   s === 'formal' ? 'Formal' :
                   s === 'sporty' ? 'Sporty' :
                   s === 'elegant' ? 'Elegant' :
                   s === 'bohemian' ? 'Bohemian' :
                   s === 'minimalist' ? 'Minimalist' : s}
                </option>
              ))}
            </select>
          </div>

          <div className="form-group">
            <label>Purchase Price (₺) *</label>
            <input 
              type="number" 
              value={purchasePrice}
              onChange={(e) => setPurchasePrice(e.target.value)}
              placeholder="e.g., 299.99"
              min="0"
              step="0.01"
              required
            />
          </div>

          <div className="form-group">
            <label>Purchase Date - Optional</label>
            <input 
              type="date" 
              value={purchaseDate}
              onChange={(e) => setPurchaseDate(e.target.value)}
            />
          </div>

          <div className="form-actions">
            <button type="button" onClick={() => navigate('/')} className="cancel-btn">
              Cancel
            </button>
            <button type="submit" className="submit-btn" disabled={loading}>
              {loading ? 'Uploading...' : 'Add & View Combinations'}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};

export default UploadPage;
