const express = require('express');
const cors = require('cors');
const bodyParser = require('body-parser');
const sqlite3 = require('sqlite3').verbose();
const multer = require('multer');
const path = require('path');
const fs = require('fs');

const app = express();
const PORT = process.env.PORT || 5001;

app.use(cors());
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: true }));
app.use('/uploads', express.static(path.join(__dirname, '../../public/uploads')));

const uploadDir = path.join(__dirname, '../../public/uploads');
if (!fs.existsSync(uploadDir)) {
  fs.mkdirSync(uploadDir, { recursive: true });
}

const storage = multer.diskStorage({
  destination: (req, file, cb) => {
    cb(null, uploadDir);
  },
  filename: (req, file, cb) => {
    const uniqueSuffix = Date.now() + '-' + Math.round(Math.random() * 1E9);
    cb(null, uniqueSuffix + path.extname(file.originalname));
  }
});

const upload = multer({ storage: storage });

const dbPath = path.join(__dirname, '../fashion_match.db');
const db = new sqlite3.Database(dbPath);

db.serialize(() => {
  db.run(`CREATE TABLE IF NOT EXISTS wardrobe_items (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT,
    category TEXT,
    color TEXT,
    style TEXT,
    image_url TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
  )`);

  db.run(`CREATE TABLE IF NOT EXISTS combinations (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT,
    items TEXT,
    description TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
  )`);

  db.run(`CREATE TABLE IF NOT EXISTS suggestions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    combination_id INTEGER,
    missing_item TEXT,
    purchase_link TEXT,
    description TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (combination_id) REFERENCES combinations(id)
  )`);

  db.run(`CREATE TABLE IF NOT EXISTS user_preferences (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    style_preference TEXT,
    color_preference TEXT,
    occasion_preference TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
  )`);
});

app.post('/api/wardrobe/upload', upload.single('image'), (req, res) => {
  try {
    if (!req.file) {
      return res.status(400).json({ error: 'No file uploaded' });
    }

    const { name, category, color, style } = req.body;
    const imageUrl = `/uploads/${req.file.filename}`;

    db.run(
      `INSERT INTO wardrobe_items (name, category, color, style, image_url) 
       VALUES (?, ?, ?, ?, ?)`,
      [name || 'Untitled Item', category || 'other', color || 'unknown', style || 'casual', imageUrl],
      function(err) {
        if (err) {
          console.error('Database error:', err);
          return res.status(500).json({ error: err.message });
        }

        const newItem = {
          id: this.lastID,
          name: name || 'Untitled Item',
          category: category || 'other',
          color: color || 'unknown',
          style: style || 'casual',
          image_url: imageUrl
        };

        db.all('SELECT * FROM wardrobe_items', [], (err, rows) => {
          if (err) {
            console.error('Error fetching wardrobe:', err);
            return res.status(500).json({ error: err.message });
          }

          if (rows.length >= 2) {
            try {
              const combinations = generateCombinations(rows);
              res.json({
                item: newItem,
                autoGeneratedCombinations: combinations.length,
                message: `${combinations.length} kombinasyon oluşturuldu`,
                shouldRedirectToSuggestions: true
              });
            } catch (comboError) {
              console.error('Error generating combinations:', comboError);
              res.json({
                item: newItem,
                autoGeneratedCombinations: 0,
                message: 'Kıyafet eklendi, kombinasyon oluşturulurken hata oluştu',
                shouldRedirectToSuggestions: false
              });
            }
          } else {
            res.json({
              item: newItem,
              autoGeneratedCombinations: 0,
              message: 'Daha fazla kıyafet ekleyerek kombinasyon oluşturabilirsiniz',
              shouldRedirectToSuggestions: false
            });
          }
        });
      }
    );
  } catch (error) {
    console.error('Upload error:', error);
    res.status(500).json({ error: error.message || 'Upload failed' });
  }
});

app.get('/api/wardrobe', (req, res) => {
  db.all('SELECT * FROM wardrobe_items ORDER BY created_at DESC', [], (err, rows) => {
    if (err) {
      return res.status(500).json({ error: err.message });
    }
    res.json(rows);
  });
});

app.delete('/api/wardrobe/:id', (req, res) => {
  const id = req.params.id;
  db.run('DELETE FROM wardrobe_items WHERE id = ?', [id], function(err) {
    if (err) {
      return res.status(500).json({ error: err.message });
    }
    res.json({ message: 'Item deleted', changes: this.changes });
  });
});

app.post('/api/combinations', (req, res) => {
  const { name, items, description } = req.body;
  const itemsJson = JSON.stringify(items);

  db.run(
    `INSERT INTO combinations (name, items, description) VALUES (?, ?, ?)`,
    [name || 'New Combination', itemsJson, description || ''],
    function(err) {
      if (err) {
        return res.status(500).json({ error: err.message });
      }
      res.json({
        id: this.lastID,
        name: name || 'New Combination',
        items: items,
        description: description || ''
      });
    }
  );
});

app.get('/api/combinations', (req, res) => {
  db.all('SELECT * FROM combinations ORDER BY created_at DESC', [], (err, rows) => {
    if (err) {
      return res.status(500).json({ error: err.message });
    }
    const combinations = rows.map(row => ({
      ...row,
      items: JSON.parse(row.items)
    }));
    res.json(combinations);
  });
});

function getPurchaseLink(category, style, color) {
  const baseUrls = {
    'shoes': 'https://www.trendyol.com/ayakkabi',
    'outerwear': 'https://www.trendyol.com/dis-giyim',
    'accessories': 'https://www.trendyol.com/aksesuar',
    'bag': 'https://www.trendyol.com/canta',
    'belt': 'https://www.trendyol.com/kemer',
    'hat': 'https://www.trendyol.com/sapka',
    'scarf': 'https://www.trendyol.com/atki-esarp'
  };

  const categoryMap = {
    'shoes': 'shoes',
    'outerwear': 'outerwear',
    'jacket': 'outerwear',
    'coat': 'outerwear',
    'blazer': 'outerwear',
    'cardigan': 'outerwear',
    'accessories': 'accessories',
    'accessory': 'accessories',
    'bag': 'bag',
    'belt': 'belt',
    'hat': 'hat',
    'scarf': 'scarf'
  };

  const mappedCategory = categoryMap[category?.toLowerCase()] || 'accessories';
  return baseUrls[mappedCategory] || 'https://www.trendyol.com';
}

function generateCombinations(wardrobeItems) {
  const combinations = [];
  const categories = {
    'top': wardrobeItems.filter(item => ['top', 'shirt', 't-shirt', 'blouse', 'sweater'].includes(item.category?.toLowerCase())),
    'bottom': wardrobeItems.filter(item => ['bottom', 'pants', 'jeans', 'skirt', 'shorts'].includes(item.category?.toLowerCase())),
    'shoes': wardrobeItems.filter(item => ['shoes', 'sneakers', 'boots', 'heels'].includes(item.category?.toLowerCase())),
    'outerwear': wardrobeItems.filter(item => ['jacket', 'coat', 'blazer', 'cardigan', 'outerwear'].includes(item.category?.toLowerCase())),
    'accessories': wardrobeItems.filter(item => ['accessory', 'accessories', 'bag', 'belt', 'hat', 'scarf'].includes(item.category?.toLowerCase()))
  };

  const maxCombinations = 20;

  for (let i = 0; i < categories.top.length && combinations.length < maxCombinations; i++) {
    for (let j = 0; j < categories.bottom.length && combinations.length < maxCombinations; j++) {
      const combination = {
        items: [categories.top[i], categories.bottom[j]].filter(Boolean),
        name: `${categories.top[i]?.name || 'Üst'} + ${categories.bottom[j]?.name || 'Alt'}`,
        missingItems: [],
        suggestions: []
      };

      if (categories.shoes.length > 0) {
        const randomShoes = categories.shoes[Math.floor(Math.random() * categories.shoes.length)];
        combination.items.push(randomShoes);
      } else {
        const topStyle = categories.top[i]?.style || 'casual';
        const topColor = categories.top[i]?.color || 'unknown';
        combination.missingItems.push({
          category: 'shoes',
          itemName: 'Ayakkabı',
          description: `${topStyle} tarzda bir ayakkabı bu kombinasyonu tamamlar`,
          purchaseLink: getPurchaseLink('shoes', topStyle, topColor)
        });
      }

      if (categories.outerwear.length > 0 && Math.random() > 0.6) {
        const randomOuterwear = categories.outerwear[Math.floor(Math.random() * categories.outerwear.length)];
        combination.items.push(randomOuterwear);
      } else if (Math.random() > 0.5) {
        const topStyle = categories.top[i]?.style || 'casual';
        combination.missingItems.push({
          category: 'outerwear',
          itemName: 'Dış Giyim',
          description: `${topStyle} tarzda bir ceket veya hırka ekleyebilirsiniz`,
          purchaseLink: getPurchaseLink('outerwear', topStyle, 'unknown')
        });
      }

      if (categories.accessories.length > 0 && Math.random() > 0.7) {
        const randomAccessory = categories.accessories[Math.floor(Math.random() * categories.accessories.length)];
        combination.items.push(randomAccessory);
      } else if (Math.random() > 0.6) {
        const topStyle = categories.top[i]?.style || 'casual';
        combination.missingItems.push({
          category: 'accessories',
          itemName: 'Aksesuar',
          description: 'Çanta, kemer veya takı gibi aksesuarlar kombinasyonu zenginleştirir',
          purchaseLink: getPurchaseLink('accessories', topStyle, 'unknown')
        });
      }

      combinations.push(combination);
    }
  }

  return combinations;
}

app.post('/api/suggestions/generate', (req, res) => {
  db.all('SELECT * FROM wardrobe_items', [], (err, rows) => {
    if (err) {
      return res.status(500).json({ error: err.message });
    }

    if (rows.length < 2) {
      return res.json({
        combinations: [],
        message: 'Add at least 2 items to your wardrobe to generate combinations'
      });
    }

    const combinations = generateCombinations(rows);
    res.json({ combinations });
  });
});

app.post('/api/suggestions/missing', (req, res) => {
  const { combinationId, missingItem, purchaseLink, description } = req.body;

  db.run(
    `INSERT INTO suggestions (combination_id, missing_item, purchase_link, description) 
     VALUES (?, ?, ?, ?)`,
    [combinationId, missingItem, purchaseLink, description],
    function(err) {
      if (err) {
        return res.status(500).json({ error: err.message });
      }
      res.json({
        id: this.lastID,
        combination_id: combinationId,
        missing_item: missingItem,
        purchase_link: purchaseLink,
        description: description
      });
    }
  );
});

app.post('/api/preferences', (req, res) => {
  const { stylePreference, colorPreference, occasionPreference } = req.body;

  db.run(
    `INSERT INTO user_preferences (style_preference, color_preference, occasion_preference) 
     VALUES (?, ?, ?)`,
    [stylePreference || 'casual', colorPreference || 'all', occasionPreference || 'daily'],
    function(err) {
      if (err) {
        return res.status(500).json({ error: err.message });
      }
      res.json({
        id: this.lastID,
        style_preference: stylePreference || 'casual',
        color_preference: colorPreference || 'all',
        occasion_preference: occasionPreference || 'daily'
      });
    }
  );
});

app.get('/api/preferences', (req, res) => {
  db.get('SELECT * FROM user_preferences ORDER BY created_at DESC LIMIT 1', [], (err, row) => {
    if (err) {
      return res.status(500).json({ error: err.message });
    }
    res.json(row || {});
  });
});

app.listen(PORT, () => {
  console.log(`Server is running on port ${PORT}`);
});

